# Generated by Django 5.1.1 on 2024-09-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_key',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
