# Generated by Django 5.1.1 on 2024-09-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_public_key_publickey'),
    ]

    operations = [
        migrations.CreateModel(
            name='E2EEKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
                ('private_key', models.CharField(help_text='This will not be the actual private key                                    rather a reference to what private key was used for this public key.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PublicKey',
        ),
    ]
