# Generated by Django 5.1.1 on 2024-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_url',
            field=models.FileField(upload_to='api/attachments/'),
        ),
    ]
