# Generated by Django 5.1.1 on 2024-09-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chatroom_options_remove_attachment_file_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchatroom',
            old_name='last_read_message',
            new_name='last_sent_message',
        ),
    ]
