# Generated by Django 5.1.1 on 2024-09-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_rename_last_read_message_userchatroom_last_sent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
