# Generated by Django 5.1.1 on 2024-09-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
