# Generated by Django 5.1.1 on 2024-09-11 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('new_group_message', 'New Group Message'), ('user_joined', 'User Joined Chat'), ('user_left', 'User Left Chat'), ('notifications_update', 'Notifications Update'), ('reaction', 'Reaction to Message')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userchatroom',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chats', to='chats.chatroom'),
        ),
    ]
