# Generated by Django 5.1.1 on 2024-09-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_notification_type_alter_userchatroom_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_message', 'sent new message'), ('reaction', 'reacted to Message'), ('user_joined_group', 'joined chat'), ('user_left_group', 'left chat'), ('notifications_update', 'Notifications Update')], max_length=50),
        ),
    ]
