# Generated by Django 5.1.1 on 2024-09-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_remove_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
