# Generated by Django 5.1.1 on 2024-09-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0015_notification_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Message', 'Message'), ('Reaction', 'Reaction'), ('ChatRoom', 'ChatRoom')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
