# Generated by Django 5.1.1 on 2024-09-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_remove_notification_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
    ]
