# Generated by Django 5.1.1 on 2024-09-11 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0018_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chats.reaction'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chats.chatroom'),
        ),
    ]
