# Generated by Django 5.1.1 on 2024-09-11 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0019_notification_reaction_alter_notification_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchatroom',
            name='last_seen_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_message', to='chats.message'),
        ),
        migrations.AlterField(
            model_name='userchatroom',
            name='last_sent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_sent_message', to='chats.message'),
        ),
    ]
