# Generated by Django 5.1.1 on 2024-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0020_message_is_edited_userchatroom_last_seen_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='userchatroom',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
