# Generated by Django 5.1.1 on 2024-09-11 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0021_remove_message_is_read_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatroom',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchatroom',
            name='last_seen_message_before_delete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_message_before_delete', to='chats.message'),
        ),
        migrations.AddField(
            model_name='userchatroom',
            name='unread_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
