# Generated by Django 5.1.1 on 2024-09-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0022_userchatroom_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatroom',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
