# Generated by Django 5.1.1 on 2024-09-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0023_alter_userchatroom_unread_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatroom',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='userchatroom',
            name='unread_count',
        ),
    ]
