# Generated by Django 5.1.1 on 2024-09-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0025_remove_chatroom_name_userchatroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reaction',
        ),
    ]
