# Generated by Django 5.1.1 on 2024-09-13 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0026_remove_notification_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
    ]
