# Generated by Django 5.1.1 on 2024-09-13 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0027_remove_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatroom',
            name='name',
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chats.chatroom'),
        ),
    ]
