# Generated by Django 5.1.1 on 2024-09-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0028_remove_userchatroom_name_alter_notification_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.BinaryField(),
        ),
    ]
