# Generated by Django 5.1.1 on 2024-09-15 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0029_alter_message_content'),
        ('users', '0007_e2eekey_delete_publickey'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='e2ee_key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.e2eekey'),
        ),
        migrations.AddField(
            model_name='message',
            name='public_key',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
